### ISSUE TITLE
Compile Error: No rule to make target 'lcd.o', needed by 'freecut.elf'

### ISSUE THREAD

**Issue by keen101** [thetazzbot/FreeExpression#13]
> make: *** No rule to make target 'lcd.o', needed by 'freecut.elf'.  Stop.

**Comment by mwhaite** [comment]
the Makefile looks out of date.  pulling the list of .c files from Debug/Makefile brings up a new set of errors.  I think I can get sometime worked out in the next few days.

**Comment by markawilliamson** [comment]
Did you get a fresh copy?  I just compiled it yesterday.  I uploaded my
local changes to github.  Apparently I fixed a lot of things and forgot to
upload it.

Regards,
Mark Williamson

**Comment by keen101** [comment]
I haven't had a chance to look at it yet

**Comment by mwhaite** [comment]
Neat.  I will check that out.  I did get it to compile in linux last night.... but didn't flash that over to my expression yet.

**Comment by keen101** [comment]
still have the error with the new pull when compiling under linux.
make: *** No rule to make target 'lcd.o', needed by 'freecut.elf'.  Stop.

@mwhaite mwhaite how did you get it to compile under linux?

I guess i can try again under windows with the Atmel studio or whatever. It was very confusing last time i tried looking at it, which is why i tried under Ubuntu Linux.

**Comment by keen101** [comment]
seems to have the same issue compiling under windows as well.

------ Build started: Project: FreeExpression_6_2, Configuration: Debug AVR ------
Build started.
Project "FreeExpression_6_2.cproj" (default targets):
Target "PreBuildEvent" skipped, due to false condition; ('$(PreBuildEvent)'!='') was evaluated as (''!='').
Target "CoreBuild" in file "C:\Program Files (x86)\Atmel\Studio\7.0\Vs\Compiler.targets" from project "C:\Users\Andrew\Downloads\FreeExpression-master\FreeExpression-master\src\FreeExpression_6_2.cproj" (target "Build" depends on it):
	Task "RunCompilerTask"
		Shell Utils Path C:\Program Files (x86)\Atmel\Studio\7.0\shellUtils
		C:\Program Files (x86)\Atmel\Studio\7.0\shellUtils\make.exe all --jobs 2 --output-sync 
		make: *** No rule to make target '.././lcd.c', needed by 'lcd.o'.  Stop.
	Done executing task "RunCompilerTask" -- FAILED.
Done building target "CoreBuild" in project "FreeExpression_6_2.cproj" -- FAILED.
Done building project "FreeExpression_6_2.cproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by mwhaite** [comment]
learned something new tonight with git.  anyhow.  I forked the repo and I think pushed my unix makefile changes.  You will need to compile and have u8glib.a I found that from https://github.com/olikraus/u8glib after compiling one of the examples.  it's a bit ugly till I figure out the submodule thing and a script to automate that.

**Comment by ellisgl** [comment]
I changed my Makefile to read:

```
# List C source files here. (C dependencies are automatically generated.)
SRC = main.c usb.c serial.c display_oled.c display.c keypad.c timer.c stepper.c cli.c flash.c dial.c hpgl.c g_code.c shvars.c scale.c
```

**Comment by ellisgl** [comment]
OK - I have done this fix in m2u8:
https://github.com/olikraus/u8glib/issues/366

Then changed my Makefile to have this:
```
# List C source files here. (C dependencies are automatically generated.)
SRC  = main.c usb.c serial.c keypad.c timer.c stepper.c cli.c flash.c display_oled.c display.c dial.c hpgl.c g_code.c shvars.c scale.c
SRC += m2u8/u8g_rect.c m2u8/u8g_circle.c m2u8/u8g_bitmap.c m2u8/u8g_clip.c m2u8/u8g_com_api.c m2u8/u8g_com_api_16gr.c m2u8/u8g_dev_ssd1325_nhd27oled_gr_new.c m2u8/u8g_page.c m2u8/u8g_com_i2c.c m2u8/u8g_com_io.c m2u8/u8g_font.c m2u8/u8g_font_data.c m2u8/u8g_line.c m2u8/u8g_state.c m2u8/u8g_cursor.c m2u8/u8g_ll_api.c m2u8/u8g_delay.c m2u8/u8g_rot.c m2u8/u8g_pb8h2.c m2u8/u8g_com_atmega_hw_spi.c m2u8/u8g_com_atmega_sw_spi.c m2u8/u8g_pb16h2.c m2u8/u8g_pb.c
```

**Comment by ellisgl** [comment]
My whole Makefile:
```
# Freecut: open firmware for Cricut Expression 1 devices.
#
# 
# MCU name
MCU = atmega1281

# Output format. (can be srec, ihex)
FORMAT = ihex

# Target file name (without extension).
TARGET = freecut

# Speed
FCLK = 16000000UL

# List C source files here. (C dependencies are automatically generated.)
SRC  = main.c usb.c serial.c keypad.c timer.c stepper.c cli.c flash.c display_oled.c display.c dial.c hpgl.c g_code.c shvars.c scale.c
SRC += m2u8/u8g_rect.c m2u8/u8g_circle.c m2u8/u8g_bitmap.c m2u8/u8g_clip.c m2u8/u8g_com_api.c m2u8/u8g_com_api_16gr.c m2u8/u8g_dev_ssd1325_nhd27oled_gr_new.c m2u8/u8g_page.c m2u8/u8g_com_i2c.c m2u8/u8g_com_io.c m2u8/u8g_font.c m2u8/u8g_font_data.c m2u8/u8g_line.c m2u8/u8g_state.c m2u8/u8g_cursor.c m2u8/u8g_ll_api.c m2u8/u8g_delay.c m2u8/u8g_rot.c m2u8/u8g_pb8h2.c m2u8/u8g_com_atmega_hw_spi.c m2u8/u8g_com_atmega_sw_spi.c m2u8/u8g_pb16h2.c m2u8/u8g_pb.c

# Assembler sources 
ASRC = 

# Optional compiler flags.
CFLAGS  = -D$(MCU) $(TEST) $(CE) -Os -DFCLK=$(FCLK) -DF_CPU=${FCLK} -fpack-struct 
CFLAGS += -fshort-enums -Wall -Werror -Wstrict-prototypes 

# Optional assembler flags.
ASFLAGS = -Wa,-ahlms=$(<:.S=.lst),-gstabs 

# Optional linker flags.
LDFLAGS = -Wl,-Map=$(TARGET).map,--cref

# Additional libraries
#
# Minimalistic printf version
#LDFLAGS += -Wl,-u,vfprintf -lprintf_min
#
# Floating point printf version (requires -lm below)
#LDFLAGS +=  -Wl,-u,vfprintf -lprintf_flt
#
# -lm = math library
LDFLAGS += -lm

# ---------------------------------------------------------------------------

# Define directories, if needed.

# Define programs and commands.
SHELL = sh

CC = avr-gcc

OBJCOPY = avr-objcopy
OBJDUMP = avr-objdump

# Define all object files.
OBJ = $(ASRC:.S=.o) $(SRC:.c=.o)

# Define all listing files.
LST = $(ASRC:.S=.lst) $(SRC:.c=.lst)

# Combine all necessary flags and optional flags. Add target processor to flags.
ALL_CFLAGS = -mmcu=$(MCU) -I. -I"./m2u8" $(CFLAGS) 
ALL_ASFLAGS = -mmcu=$(MCU) -I. -x assembler-with-cpp $(ASFLAGS)

# Default target.
all: $(TARGET).elf $(TARGET).hex $(TARGET).lss tags

.PHONY: prog 

#you may need to change this line to program your device
prog: all 
	avrdude -pm128 -cstk500v2 -b115200 -P/dev/ttyUSB0 -u -V -U flash:w:$(TARGET).hex:i 

# Create final output files (.hex) from ELF output file.
%.hex: %.elf
	$(OBJCOPY) -O $(FORMAT) -R .eeprom $< $@

# Disassembly listing
%.dis: %.elf
	$(OBJDUMP) -d $< > $@

# Create extended listing file from ELF output file.
%.lss: %.elf
	$(OBJDUMP) -h -S $< > $@

# Link: create ELF output file from object files.
.SECONDARY : $(TARGET).elf
.PRECIOUS : $(OBJ)
%.elf: $(OBJ)
	$(CC) $(ALL_CFLAGS) $(OBJ) --output $@ $(LDFLAGS)


# Compile: create object files from C source files.
%.o : %.c
	$(CC) -c $(ALL_CFLAGS) $< -o $@


# Compile: create assembler files from C source files.
%.s : %.c
	$(CC) -S $(ALL_CFLAGS) $< -o $@


# Assemble: create object files from assembler source files.
%.o : %.S
	$(CC) -c $(ALL_ASFLAGS) $< -o $@


# Target: clean project.

clean :
	rm -f *.hex
	rm -f *.obj
	rm -f *.elf
	rm -f *.map
	rm -f *.obj
	rm -f *.sym
	rm -f *.ssm
	rm -f *.lnk
	rm -f *.lss
	rm -f *.lst
	rm -f $(OBJ)
	rm -f $(LST)
	rm -f $(SRC:.c=.s)
	rm -f $(SRC:.c=.d)
	rm -f logfile


# Automatically generate C source code dependencies. 
# (Code originally taken from the GNU make user manual and modified (See README.txt Credits).)
# Note that this will work with sh (bash) and sed that is shipped with WinAVR (see the SHELL variable defined above).
# This may not work with other shells or other seds.
%.d: %.c
	set -e; $(CC) -MM $(ALL_CFLAGS) $< \
	| sed  -e 's,\(.*\)\.o[ :]*,\1.o \1.d : ,g' \
	> $@; [ -s $@ ] || rm -f $@


# Remove the '-' if you want to see the dependency files generated.
-include $(SRC:.c=.d)


# Listing of phony targets.
.PHONY : all clean 

tags: *.[hc]
	ctags *.[hc]
```

**Comment by dolfelt** [comment]
I am also running into this issue @mwhaite. Care to share any more details on how you got that complied? It seems that there are `u8glib` source files in the repository but don't get compiled as part of the `Makefile`

Thanks!

**Comment by ellisgl** [comment]
I ended up making a fork to get this all working: https://github.com/ellisgl/FreeExpression

**Comment by dolfelt** [comment]
@ellisgl were you able to get the machine working? I was able to compile everything and get it moving and the buttons functioning. I even updated the oled library to `u8g2` and made some performance improvements, but I was never able to get it to plot from Inkscape. It would intermittently do a single command, but never more than one, and really didn't look like the shape I was trying to cut out.

Any thoughts or help would be appreciated. After several days of tinkering I'm closing to giving up and using my 3D printer or CNC with a drag knife to cut stuff out.

**Comment by ellisgl** [comment]
IIRC I had it working. I've haven't had much time to tinker with it since I did my branch and had the cartridge ISP boards made (which I have 9 sitting around).
